// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: account.proto
// Protobuf Java Version: 4.27.2

package account;

public final class Account {
  private Account() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 27,
      /* patch= */ 2,
      /* suffix= */ "",
      Account.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LoginRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:account.LoginRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string username = 2;</code>
     * @return The username.
     */
    java.lang.String getUsername();
    /**
     * <code>string username = 2;</code>
     * @return The bytes for username.
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>string password = 3;</code>
     * @return The password.
     */
    java.lang.String getPassword();
    /**
     * <code>string password = 3;</code>
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * <pre>
   * 示例
   * </pre>
   *
   * Protobuf type {@code account.LoginRequest}
   */
  public static final class LoginRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:account.LoginRequest)
      LoginRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        LoginRequest.class.getName());
    }
    // Use LoginRequest.newBuilder() to construct.
    private LoginRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private LoginRequest() {
      username_ = "";
      password_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return account.Account.internal_static_account_LoginRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return account.Account.internal_static_account_LoginRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              account.Account.LoginRequest.class, account.Account.LoginRequest.Builder.class);
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object username_ = "";
    /**
     * <code>string username = 2;</code>
     * @return The username.
     */
    @java.lang.Override
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }
    /**
     * <code>string username = 2;</code>
     * @return The bytes for username.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PASSWORD_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object password_ = "";
    /**
     * <code>string password = 3;</code>
     * @return The password.
     */
    @java.lang.Override
    public java.lang.String getPassword() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        password_ = s;
        return s;
      }
    }
    /**
     * <code>string password = 3;</code>
     * @return The bytes for password.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      java.lang.Object ref = password_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        password_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(username_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, username_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(password_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, password_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(username_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, username_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(password_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, password_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof account.Account.LoginRequest)) {
        return super.equals(obj);
      }
      account.Account.LoginRequest other = (account.Account.LoginRequest) obj;

      if (!getUsername()
          .equals(other.getUsername())) return false;
      if (!getPassword()
          .equals(other.getPassword())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
      hash = (53 * hash) + getPassword().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static account.Account.LoginRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static account.Account.LoginRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static account.Account.LoginRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static account.Account.LoginRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static account.Account.LoginRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static account.Account.LoginRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static account.Account.LoginRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static account.Account.LoginRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static account.Account.LoginRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static account.Account.LoginRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static account.Account.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static account.Account.LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(account.Account.LoginRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 示例
     * </pre>
     *
     * Protobuf type {@code account.LoginRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:account.LoginRequest)
        account.Account.LoginRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return account.Account.internal_static_account_LoginRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return account.Account.internal_static_account_LoginRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                account.Account.LoginRequest.class, account.Account.LoginRequest.Builder.class);
      }

      // Construct using account.Account.LoginRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        username_ = "";
        password_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return account.Account.internal_static_account_LoginRequest_descriptor;
      }

      @java.lang.Override
      public account.Account.LoginRequest getDefaultInstanceForType() {
        return account.Account.LoginRequest.getDefaultInstance();
      }

      @java.lang.Override
      public account.Account.LoginRequest build() {
        account.Account.LoginRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public account.Account.LoginRequest buildPartial() {
        account.Account.LoginRequest result = new account.Account.LoginRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(account.Account.LoginRequest result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.username_ = username_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.password_ = password_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof account.Account.LoginRequest) {
          return mergeFrom((account.Account.LoginRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(account.Account.LoginRequest other) {
        if (other == account.Account.LoginRequest.getDefaultInstance()) return this;
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getPassword().isEmpty()) {
          password_ = other.password_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 18: {
                username_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 18
              case 26: {
                password_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object username_ = "";
      /**
       * <code>string username = 2;</code>
       * @return The username.
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string username = 2;</code>
       * @return The bytes for username.
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string username = 2;</code>
       * @param value The username to set.
       * @return This builder for chaining.
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        username_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string username = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsername() {
        username_ = getDefaultInstance().getUsername();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string username = 2;</code>
       * @param value The bytes for username to set.
       * @return This builder for chaining.
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        username_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object password_ = "";
      /**
       * <code>string password = 3;</code>
       * @return The password.
       */
      public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          password_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string password = 3;</code>
       * @return The bytes for password.
       */
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          password_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string password = 3;</code>
       * @param value The password to set.
       * @return This builder for chaining.
       */
      public Builder setPassword(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        password_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string password = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassword() {
        password_ = getDefaultInstance().getPassword();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string password = 3;</code>
       * @param value The bytes for password to set.
       * @return This builder for chaining.
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        password_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:account.LoginRequest)
    }

    // @@protoc_insertion_point(class_scope:account.LoginRequest)
    private static final account.Account.LoginRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new account.Account.LoginRequest();
    }

    public static account.Account.LoginRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginRequest>
        PARSER = new com.google.protobuf.AbstractParser<LoginRequest>() {
      @java.lang.Override
      public LoginRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LoginRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public account.Account.LoginRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LoginResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:account.LoginResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>fixed32 aaa = 1;</code>
     * @return The aaa.
     */
    int getAaa();

    /**
     * <code>fixed32 bbb = 2;</code>
     * @return The bbb.
     */
    int getBbb();
  }
  /**
   * <pre>
   * 示例
   * </pre>
   *
   * Protobuf type {@code account.LoginResponse}
   */
  public static final class LoginResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:account.LoginResponse)
      LoginResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        LoginResponse.class.getName());
    }
    // Use LoginResponse.newBuilder() to construct.
    private LoginResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private LoginResponse() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return account.Account.internal_static_account_LoginResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return account.Account.internal_static_account_LoginResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              account.Account.LoginResponse.class, account.Account.LoginResponse.Builder.class);
    }

    public static final int AAA_FIELD_NUMBER = 1;
    private int aaa_ = 0;
    /**
     * <code>fixed32 aaa = 1;</code>
     * @return The aaa.
     */
    @java.lang.Override
    public int getAaa() {
      return aaa_;
    }

    public static final int BBB_FIELD_NUMBER = 2;
    private int bbb_ = 0;
    /**
     * <code>fixed32 bbb = 2;</code>
     * @return The bbb.
     */
    @java.lang.Override
    public int getBbb() {
      return bbb_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (aaa_ != 0) {
        output.writeFixed32(1, aaa_);
      }
      if (bbb_ != 0) {
        output.writeFixed32(2, bbb_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (aaa_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(1, aaa_);
      }
      if (bbb_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(2, bbb_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof account.Account.LoginResponse)) {
        return super.equals(obj);
      }
      account.Account.LoginResponse other = (account.Account.LoginResponse) obj;

      if (getAaa()
          != other.getAaa()) return false;
      if (getBbb()
          != other.getBbb()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AAA_FIELD_NUMBER;
      hash = (53 * hash) + getAaa();
      hash = (37 * hash) + BBB_FIELD_NUMBER;
      hash = (53 * hash) + getBbb();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static account.Account.LoginResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static account.Account.LoginResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static account.Account.LoginResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static account.Account.LoginResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static account.Account.LoginResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static account.Account.LoginResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static account.Account.LoginResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static account.Account.LoginResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static account.Account.LoginResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static account.Account.LoginResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static account.Account.LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static account.Account.LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(account.Account.LoginResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 示例
     * </pre>
     *
     * Protobuf type {@code account.LoginResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:account.LoginResponse)
        account.Account.LoginResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return account.Account.internal_static_account_LoginResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return account.Account.internal_static_account_LoginResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                account.Account.LoginResponse.class, account.Account.LoginResponse.Builder.class);
      }

      // Construct using account.Account.LoginResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        aaa_ = 0;
        bbb_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return account.Account.internal_static_account_LoginResponse_descriptor;
      }

      @java.lang.Override
      public account.Account.LoginResponse getDefaultInstanceForType() {
        return account.Account.LoginResponse.getDefaultInstance();
      }

      @java.lang.Override
      public account.Account.LoginResponse build() {
        account.Account.LoginResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public account.Account.LoginResponse buildPartial() {
        account.Account.LoginResponse result = new account.Account.LoginResponse(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(account.Account.LoginResponse result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.aaa_ = aaa_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.bbb_ = bbb_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof account.Account.LoginResponse) {
          return mergeFrom((account.Account.LoginResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(account.Account.LoginResponse other) {
        if (other == account.Account.LoginResponse.getDefaultInstance()) return this;
        if (other.getAaa() != 0) {
          setAaa(other.getAaa());
        }
        if (other.getBbb() != 0) {
          setBbb(other.getBbb());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 13: {
                aaa_ = input.readFixed32();
                bitField0_ |= 0x00000001;
                break;
              } // case 13
              case 21: {
                bbb_ = input.readFixed32();
                bitField0_ |= 0x00000002;
                break;
              } // case 21
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int aaa_ ;
      /**
       * <code>fixed32 aaa = 1;</code>
       * @return The aaa.
       */
      @java.lang.Override
      public int getAaa() {
        return aaa_;
      }
      /**
       * <code>fixed32 aaa = 1;</code>
       * @param value The aaa to set.
       * @return This builder for chaining.
       */
      public Builder setAaa(int value) {

        aaa_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>fixed32 aaa = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAaa() {
        bitField0_ = (bitField0_ & ~0x00000001);
        aaa_ = 0;
        onChanged();
        return this;
      }

      private int bbb_ ;
      /**
       * <code>fixed32 bbb = 2;</code>
       * @return The bbb.
       */
      @java.lang.Override
      public int getBbb() {
        return bbb_;
      }
      /**
       * <code>fixed32 bbb = 2;</code>
       * @param value The bbb to set.
       * @return This builder for chaining.
       */
      public Builder setBbb(int value) {

        bbb_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>fixed32 bbb = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearBbb() {
        bitField0_ = (bitField0_ & ~0x00000002);
        bbb_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:account.LoginResponse)
    }

    // @@protoc_insertion_point(class_scope:account.LoginResponse)
    private static final account.Account.LoginResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new account.Account.LoginResponse();
    }

    public static account.Account.LoginResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginResponse>
        PARSER = new com.google.protobuf.AbstractParser<LoginResponse>() {
      @java.lang.Override
      public LoginResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<LoginResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public account.Account.LoginResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TempRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:account.TempRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.monon.messs ss = 1;</code>
     * @return Whether the ss field is set.
     */
    boolean hasSs();
    /**
     * <code>.monon.messs ss = 1;</code>
     * @return The ss.
     */
    monon.Monon.messs getSs();
    /**
     * <code>.monon.messs ss = 1;</code>
     */
    monon.Monon.messsOrBuilder getSsOrBuilder();

    /**
     * <code>fixed32 aaa = 2;</code>
     * @return The aaa.
     */
    int getAaa();

    /**
     * <code>fixed32 bbb = 3;</code>
     * @return The bbb.
     */
    int getBbb();
  }
  /**
   * <pre>
   * 示例
   * </pre>
   *
   * Protobuf type {@code account.TempRequest}
   */
  public static final class TempRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:account.TempRequest)
      TempRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 27,
        /* patch= */ 2,
        /* suffix= */ "",
        TempRequest.class.getName());
    }
    // Use TempRequest.newBuilder() to construct.
    private TempRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private TempRequest() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return account.Account.internal_static_account_TempRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return account.Account.internal_static_account_TempRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              account.Account.TempRequest.class, account.Account.TempRequest.Builder.class);
    }

    private int bitField0_;
    public static final int SS_FIELD_NUMBER = 1;
    private monon.Monon.messs ss_;
    /**
     * <code>.monon.messs ss = 1;</code>
     * @return Whether the ss field is set.
     */
    @java.lang.Override
    public boolean hasSs() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.monon.messs ss = 1;</code>
     * @return The ss.
     */
    @java.lang.Override
    public monon.Monon.messs getSs() {
      return ss_ == null ? monon.Monon.messs.getDefaultInstance() : ss_;
    }
    /**
     * <code>.monon.messs ss = 1;</code>
     */
    @java.lang.Override
    public monon.Monon.messsOrBuilder getSsOrBuilder() {
      return ss_ == null ? monon.Monon.messs.getDefaultInstance() : ss_;
    }

    public static final int AAA_FIELD_NUMBER = 2;
    private int aaa_ = 0;
    /**
     * <code>fixed32 aaa = 2;</code>
     * @return The aaa.
     */
    @java.lang.Override
    public int getAaa() {
      return aaa_;
    }

    public static final int BBB_FIELD_NUMBER = 3;
    private int bbb_ = 0;
    /**
     * <code>fixed32 bbb = 3;</code>
     * @return The bbb.
     */
    @java.lang.Override
    public int getBbb() {
      return bbb_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(1, getSs());
      }
      if (aaa_ != 0) {
        output.writeFixed32(2, aaa_);
      }
      if (bbb_ != 0) {
        output.writeFixed32(3, bbb_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSs());
      }
      if (aaa_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(2, aaa_);
      }
      if (bbb_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFixed32Size(3, bbb_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof account.Account.TempRequest)) {
        return super.equals(obj);
      }
      account.Account.TempRequest other = (account.Account.TempRequest) obj;

      if (hasSs() != other.hasSs()) return false;
      if (hasSs()) {
        if (!getSs()
            .equals(other.getSs())) return false;
      }
      if (getAaa()
          != other.getAaa()) return false;
      if (getBbb()
          != other.getBbb()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSs()) {
        hash = (37 * hash) + SS_FIELD_NUMBER;
        hash = (53 * hash) + getSs().hashCode();
      }
      hash = (37 * hash) + AAA_FIELD_NUMBER;
      hash = (53 * hash) + getAaa();
      hash = (37 * hash) + BBB_FIELD_NUMBER;
      hash = (53 * hash) + getBbb();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static account.Account.TempRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static account.Account.TempRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static account.Account.TempRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static account.Account.TempRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static account.Account.TempRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static account.Account.TempRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static account.Account.TempRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static account.Account.TempRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static account.Account.TempRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static account.Account.TempRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static account.Account.TempRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static account.Account.TempRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(account.Account.TempRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 示例
     * </pre>
     *
     * Protobuf type {@code account.TempRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:account.TempRequest)
        account.Account.TempRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return account.Account.internal_static_account_TempRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return account.Account.internal_static_account_TempRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                account.Account.TempRequest.class, account.Account.TempRequest.Builder.class);
      }

      // Construct using account.Account.TempRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getSsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        ss_ = null;
        if (ssBuilder_ != null) {
          ssBuilder_.dispose();
          ssBuilder_ = null;
        }
        aaa_ = 0;
        bbb_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return account.Account.internal_static_account_TempRequest_descriptor;
      }

      @java.lang.Override
      public account.Account.TempRequest getDefaultInstanceForType() {
        return account.Account.TempRequest.getDefaultInstance();
      }

      @java.lang.Override
      public account.Account.TempRequest build() {
        account.Account.TempRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public account.Account.TempRequest buildPartial() {
        account.Account.TempRequest result = new account.Account.TempRequest(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(account.Account.TempRequest result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.ss_ = ssBuilder_ == null
              ? ss_
              : ssBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.aaa_ = aaa_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.bbb_ = bbb_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof account.Account.TempRequest) {
          return mergeFrom((account.Account.TempRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(account.Account.TempRequest other) {
        if (other == account.Account.TempRequest.getDefaultInstance()) return this;
        if (other.hasSs()) {
          mergeSs(other.getSs());
        }
        if (other.getAaa() != 0) {
          setAaa(other.getAaa());
        }
        if (other.getBbb() != 0) {
          setBbb(other.getBbb());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                input.readMessage(
                    getSsFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 21: {
                aaa_ = input.readFixed32();
                bitField0_ |= 0x00000002;
                break;
              } // case 21
              case 29: {
                bbb_ = input.readFixed32();
                bitField0_ |= 0x00000004;
                break;
              } // case 29
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private monon.Monon.messs ss_;
      private com.google.protobuf.SingleFieldBuilder<
          monon.Monon.messs, monon.Monon.messs.Builder, monon.Monon.messsOrBuilder> ssBuilder_;
      /**
       * <code>.monon.messs ss = 1;</code>
       * @return Whether the ss field is set.
       */
      public boolean hasSs() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.monon.messs ss = 1;</code>
       * @return The ss.
       */
      public monon.Monon.messs getSs() {
        if (ssBuilder_ == null) {
          return ss_ == null ? monon.Monon.messs.getDefaultInstance() : ss_;
        } else {
          return ssBuilder_.getMessage();
        }
      }
      /**
       * <code>.monon.messs ss = 1;</code>
       */
      public Builder setSs(monon.Monon.messs value) {
        if (ssBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ss_ = value;
        } else {
          ssBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.monon.messs ss = 1;</code>
       */
      public Builder setSs(
          monon.Monon.messs.Builder builderForValue) {
        if (ssBuilder_ == null) {
          ss_ = builderForValue.build();
        } else {
          ssBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.monon.messs ss = 1;</code>
       */
      public Builder mergeSs(monon.Monon.messs value) {
        if (ssBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0) &&
            ss_ != null &&
            ss_ != monon.Monon.messs.getDefaultInstance()) {
            getSsBuilder().mergeFrom(value);
          } else {
            ss_ = value;
          }
        } else {
          ssBuilder_.mergeFrom(value);
        }
        if (ss_ != null) {
          bitField0_ |= 0x00000001;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.monon.messs ss = 1;</code>
       */
      public Builder clearSs() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ss_ = null;
        if (ssBuilder_ != null) {
          ssBuilder_.dispose();
          ssBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.monon.messs ss = 1;</code>
       */
      public monon.Monon.messs.Builder getSsBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSsFieldBuilder().getBuilder();
      }
      /**
       * <code>.monon.messs ss = 1;</code>
       */
      public monon.Monon.messsOrBuilder getSsOrBuilder() {
        if (ssBuilder_ != null) {
          return ssBuilder_.getMessageOrBuilder();
        } else {
          return ss_ == null ?
              monon.Monon.messs.getDefaultInstance() : ss_;
        }
      }
      /**
       * <code>.monon.messs ss = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          monon.Monon.messs, monon.Monon.messs.Builder, monon.Monon.messsOrBuilder> 
          getSsFieldBuilder() {
        if (ssBuilder_ == null) {
          ssBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              monon.Monon.messs, monon.Monon.messs.Builder, monon.Monon.messsOrBuilder>(
                  getSs(),
                  getParentForChildren(),
                  isClean());
          ss_ = null;
        }
        return ssBuilder_;
      }

      private int aaa_ ;
      /**
       * <code>fixed32 aaa = 2;</code>
       * @return The aaa.
       */
      @java.lang.Override
      public int getAaa() {
        return aaa_;
      }
      /**
       * <code>fixed32 aaa = 2;</code>
       * @param value The aaa to set.
       * @return This builder for chaining.
       */
      public Builder setAaa(int value) {

        aaa_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>fixed32 aaa = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAaa() {
        bitField0_ = (bitField0_ & ~0x00000002);
        aaa_ = 0;
        onChanged();
        return this;
      }

      private int bbb_ ;
      /**
       * <code>fixed32 bbb = 3;</code>
       * @return The bbb.
       */
      @java.lang.Override
      public int getBbb() {
        return bbb_;
      }
      /**
       * <code>fixed32 bbb = 3;</code>
       * @param value The bbb to set.
       * @return This builder for chaining.
       */
      public Builder setBbb(int value) {

        bbb_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>fixed32 bbb = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBbb() {
        bitField0_ = (bitField0_ & ~0x00000004);
        bbb_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:account.TempRequest)
    }

    // @@protoc_insertion_point(class_scope:account.TempRequest)
    private static final account.Account.TempRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new account.Account.TempRequest();
    }

    public static account.Account.TempRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TempRequest>
        PARSER = new com.google.protobuf.AbstractParser<TempRequest>() {
      @java.lang.Override
      public TempRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<TempRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TempRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public account.Account.TempRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_account_LoginRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_account_LoginRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_account_LoginResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_account_LoginResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_account_TempRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_account_TempRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\raccount.proto\022\007account\032\013monon.proto\"2\n" +
      "\014LoginRequest\022\020\n\010username\030\002 \001(\t\022\020\n\010passw" +
      "ord\030\003 \001(\t\")\n\rLoginResponse\022\013\n\003aaa\030\001 \001(\007\022" +
      "\013\n\003bbb\030\002 \001(\007\"A\n\013TempRequest\022\030\n\002ss\030\001 \001(\0132" +
      "\014.monon.messs\022\013\n\003aaa\030\002 \001(\007\022\013\n\003bbb\030\003 \001(\007B" +
      "\013B\007AccountP\000b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          monon.Monon.getDescriptor(),
        });
    internal_static_account_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_account_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_account_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_account_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_account_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_account_LoginResponse_descriptor,
        new java.lang.String[] { "Aaa", "Bbb", });
    internal_static_account_TempRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_account_TempRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_account_TempRequest_descriptor,
        new java.lang.String[] { "Ss", "Aaa", "Bbb", });
    descriptor.resolveAllFeaturesImmutable();
    monon.Monon.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
